#数据源配置
spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    druid:
      db1:
        url: jdbc:mysql://localhost:3306/db1
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db2:
        url: jdbc:mysql://localhost:3306/db2
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db3:
        url: jdbc:mysql://localhost:3306/db3
        username: root
        password: admin
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20


mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)